### ISSUE TITLE
Issue Dumping network to dat file

### ISSUE THREAD

**Issue by MaajidKhan** [harmanpreet93/keras-model-to-cpp#1]
Hey, I have issue while dumping the network into dat file.
Basically, 2nd step :
 2. Dump network to dat file `python dump_to_cpp.py -a arch.json -w weights.h5 -o dumped_nn.dat`.

while, I run this script dump_to_cpp.py , it throws an error:

Using TensorFlow backend.
Read architecture from arch.json
Read weights from weights.h5
Writing to converted_to_cpp.dat
0 name
Traceback (most recent call last):
  File "dump_to_cpp.py", line 36, in <module>
    fout.write('layer ' + str(ind) + ' ' + l['class_name'] + '\n')
TypeError: string indices must be integers

The issue is, l should have been of data type 'list' but in our case it is a 'string'.

can you please rectify this issue and provide a working solution.

**Comment by abdulwaheedsoudagar** [comment]
I think it is due to version difference, It can be solved by adding **'layers'** in line 38 like her
 <br>       **_for ind, l in enumerate(arch["config"]['layers']):_**

**Comment by abdulwaheedsoudagar** [comment]
> Hey, I have issue while dumping the network into dat file.
> Basically, 2nd step :
> 2. Dump network to dat file `python dump_to_cpp.py -a arch.json -w weights.h5 -o dumped_nn.dat`.
> 
> while, I run this script dump_to_cpp.py , it throws an error:
> 
> Using TensorFlow backend.
> Read architecture from arch.json
> Read weights from weights.h5
> Writing to converted_to_cpp.dat
> 0 name
> Traceback (most recent call last):
> File "dump_to_cpp.py", line 36, in
> fout.write('layer ' + str(ind) + ' ' + l['class_name'] + '\n')
> TypeError: string indices must be integers
> 
> The issue is, l should have been of data type 'list' but in our case it is a 'string'.
> 
> can you please rectify this issue and provide a working solution.

I think it is due to version difference, It can be solved by adding 'layers' in line 38 like this

for ind, l in enumerate(arch["config"]['layers']):
